### PR TITLE
Fix / ERC1155 token card fixed price sale cases

### LINKED ISSUE #483: Allow purchase of 1155 when we are owner
If we own items of an ERC1155, the button displayed in the card displays the wrong text and the cart button is disabled. We should be able to purchase as long as we have an offer available for us https://github.com/liteflow-labs/starter-kit/pull/476/commits/cf445d82992763c8bf08b173e1dd0fc4522778ec

### PR DESCRIPTION
**Pull request by ismailToyran**
### Project organization

- Closes #483 
- Related [trello card](https://trello.com/c/5ueJPkeR/1196-issue-allow-purchase-of-1155-when-we-are-owner)

### Description
- Fix wrong text case for ERC1155 token card
- Fix disabled cart add button case for ERC1155 on token card
- Fix not logged in user case for token card

### Further improvement
is tracked on https://github.com/liteflow-labs/starter-kit/issues/529
Need to brainstorm

### Checklist
- [x] Base branch of the PR is `dev`

### CODE REVIEW

File: components/Sales/Direct/CardFooter.tsx [hunk 1]
```diff
@@ -94,7 +106,7 @@ const SaleDirectCardFooter: FC<Props> = ({
             : chip}
         </Text>
       </Flex>
-      {showButton && (
+      {showButton && address && (
```
Comment (antho1404) [inline components/Sales/Direct/CardFooter.tsx:109]: It's not ideal for this one; that fixes a bug, but maybe we can think of a better system where we don't hide the button or just disable it.
For now, we can keep it like that; I will create an issue.

**Review by antho1404 — APPROVED** [review]
